import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { decodeMethodologyBundle } from "./bundle-decoder.js";

export type MethodologyCatalogFormatter = (fileName: string, source: string) => Promise<string>;

const allowlist = new Map([
  ["paseo/standard@1", "sha256:d5001287a60f868bcef21ecd3c4debb5a5237db002c5b9d0f7b0b78e98969697"],
  [
    "portable/software-delivery@1",
    "sha256:5c86942af2427e89c28af9b7818fe61352423811264973dc4742cc2d1619e56c",
  ],
]);

interface ManifestEntry {
  bundleId: string;
  version: string;
  digest: string;
  path: string;
  byteLength: number;
  name: string;
}

async function bundleFiles(root: string, directory = resolve(root, "bundles")): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) =>
      entry.isDirectory()
        ? bundleFiles(root, resolve(directory, entry.name))
        : [relative(root, resolve(directory, entry.name))],
    ),
  );
  return files.flat().sort();
}

export async function syncMethodologyCatalog(input: {
  source: string;
  output: string;
  formatSource: MethodologyCatalogFormatter;
}): Promise<"clean" | "changed"> {
  const manifest = JSON.parse(await readFile(resolve(input.source, "manifest.json"), "utf8")) as {
    package: { name: string; version: string };
    bundles: ManifestEntry[];
  };
  if (
    manifest.package.name !== "@team-harness/methodologies" ||
    manifest.package.version !== "0.2.0"
  ) {
    throw new Error("Unexpected methodology package identity");
  }
  const files = await bundleFiles(input.source);
  const manifestFiles = manifest.bundles.map((entry) => entry.path).sort();
  if (JSON.stringify(files) !== JSON.stringify(manifestFiles))
    throw new Error("Bundle files do not match manifest");

  const seen = new Set<string>();
  const entries = [];
  for (const entry of manifest.bundles) {
    const ref = `${entry.bundleId}@${entry.version}`;
    if (seen.has(ref)) throw new Error(`Duplicate methodology ref ${ref}`);
    seen.add(ref);
    if (allowlist.get(ref) !== entry.digest)
      throw new Error(`Methodology ${ref} is not allowlisted`);
    const bytes = await readFile(resolve(input.source, entry.path));
    const byteDigest = `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
    if (bytes.length !== entry.byteLength || byteDigest !== entry.digest)
      throw new Error(`Corrupt methodology ${ref}`);
    const { digest: _verifiedDigest, ...bundle } = decodeMethodologyBundle(bytes, entry.digest);
    entries.push({ ref, digest: entry.digest, bundle });
  }
  if (seen.size !== allowlist.size || [...allowlist.keys()].some((ref) => !seen.has(ref))) {
    throw new Error("Methodology allowlist is incomplete");
  }
  const source = `// Generated by sync-methodology-catalog.ts. Do not edit.\nimport type { MethodologyBundleV1 } from "./bundle-decoder.js";\n\nexport const EMBEDDED_METHODOLOGIES = ${JSON.stringify(entries, null, 2)} as const satisfies readonly { ref: string; digest: string; bundle: MethodologyBundleV1 }[];\n`;
  const generated = await input.formatSource(input.output, source);
  let current: string | null = null;
  try {
    current = await readFile(input.output, "utf8");
  } catch {}
  if (current === generated) return "clean";
  await mkdir(dirname(input.output), { recursive: true });
  await writeFile(input.output, generated);
  return "changed";
}
